name: Publish Next Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-22.04
    container:
      image: pivotalrabbitmq/website-packaging
    steps:
      - uses: actions/checkout@v4
      - name: Generate next website
        id: generate
        run: |
          mkdir generated
          ./generate ./generated next
          cp "conf/robots.txt-next" ./generated/robots.txt
          tar -zcf generated.tar.xz generated
      - name: Upload generated website
        uses: actions/upload-artifact@v3
        with:
          name: generated
          path: generated.tar.xz
  publish:
    runs-on: ubuntu-22.04
    needs: generate
    steps:
      - name: Checkout rabbitmq-website
        uses: actions/checkout@v4
        with:
          path: 'rabbitmq-website'
      - name: Checkout rabbitmq-website-next
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/rabbitmq-website-next
          path: 'rabbitmq-website-next'
          ssh-key: ${{ secrets.RABBITMQ_CI_PRIVATE_KEY }}
      - name: Download generated website
        uses: actions/download-artifact@v3
        with:
          name: generated
      - name: Decompress generated website
        run: tar xzf generated.tar.xz
      - name: Publish next website
        run: rabbitmq-website/ci/publish-next.sh
